// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCq3912Vifotb8zmoivQyjCAHY1mphdMM',
    appId: '1:667327915174:web:b256c4f1066340bab8c067',
    messagingSenderId: '667327915174',
    projectId: 'e-book-okba-store',
    authDomain: 'e-book-okba-store.firebaseapp.com',
    storageBucket: 'e-book-okba-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATGV__w21x19nHrWk4G8SEwPx88HDzCIE',
    appId: '1:667327915174:android:ecd4d91fae123d93b8c067',
    messagingSenderId: '667327915174',
    projectId: 'e-book-okba-store',
    storageBucket: 'e-book-okba-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7vtd14w9bTqnq42lcpETUaHav7r0LjIc',
    appId: '1:667327915174:ios:4c5686fa05309fb0b8c067',
    messagingSenderId: '667327915174',
    projectId: 'e-book-okba-store',
    storageBucket: 'e-book-okba-store.appspot.com',
    iosBundleId: 'com.example.eBookOkbaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7vtd14w9bTqnq42lcpETUaHav7r0LjIc',
    appId: '1:667327915174:ios:cad32ecd45ad0422b8c067',
    messagingSenderId: '667327915174',
    projectId: 'e-book-okba-store',
    storageBucket: 'e-book-okba-store.appspot.com',
    iosBundleId: 'com.example.eBookOkbaStore.RunnerTests',
  );
}
